version: "3"
services:
  appdb:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DB_LANG=ja_JP
    container_name: "pg15-db"
    environment:
      - POSTGRES_USER=suburi
      - POSTGRES_PASSWORD=suburi
      - POSTGRES_DB=suburi
      - TZ="Asia/Tokyo"
    ports:
      - "15432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
